#!/usr/bin/env python
# -*- coding: utf-8 -*-

top='.'
out='build'

def options(opt):
    opt.load('compiler_c')
    opt.load('compiler_cxx')
 
    #Dummy way to replace the default of install prefix
    PREFIX_DEFAULT = "."   
    opt.add_option('--prefix', action='store', default=PREFIX_DEFAULT
                             , help="installation prefix [defaults to '%s']" % PREFIX_DEFAULT)
    
def configure(conf):
    #Load features
    conf.load('compiler_c')
    conf.load('compiler_cxx')

def build(bld):
    bld.shlib( target='hellolib'
               , source=bld.path.ant_glob('src/**.cpp')
               , install="${PREFIX}")

